import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";
import { ThemeProvider } from "@/components/providers/theme-provider";
import { AppLayout } from "@/components/app-layout";
import { TRPCReactProvider } from "@/trpc/client";
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import { Provider } from "jotai";


export const metadata: Metadata = {
  title: "Aethon",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased"
      >
        <TRPCReactProvider>
          <NuqsAdapter>
            <Provider>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
          >
              <AppLayout>{children}</AppLayout>
              <Toaster/>
          </ThemeProvider>
          </Provider>
            </NuqsAdapter>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
